import Head from "next/head";
import Link from "next/link";
import NavigationBar from "@/component/NavigationBar";
import AnimalList from "@/component/AnimalsList";

export default function Home() {
  return (
    <>
      <NavigationBar />
      <Head>
        <title>Hallo World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AnimalList kind="cow" />;
    </>
  );
}

interface NewNavItemProps {
  href: string;
  text: string;
}

const NewNavItem = (props: NewNavItemProps) => {
  const href = props.href;
  const text = props.text;
  return (
    <li>
      <Link href={href}>{text}</Link>
    </li>
  );
};
