import Head from "next/head";
import Link from "next/link";
import NavigationBar from "@/component/NavigationBar";

export default function Home() {
  return (
    <>
      <NavigationBar />
      <Head>
        <title>Hallo World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      ;
    </>
  );
}

interface NewNavItemProps {
  href: string;
  text: string;
}

const NewNavItem = (props: NewNavItemProps) => {
  const href = props.href;
  const text = props.text;
  return (
    <li>
      <Link href={href}>{text}</Link>
    </li>
  );
};

// const NavigationBar = () => {
//   return (
//     <nav>
//       <ul>
//         <NewNavItem text="Home" href="/" />
//         <NewNavItem text="About" href="/about" />
//         <NewNavItem text="Contact" href="/contact" />
//         <NewNavItem text="Animals" href="/Animals" />
//         <NewNavItem text="cows" href="/cows" />
//       </ul>
//     </nav>
//   );
// };
